### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/pubnub#1]
Let me know when you're done with the code, tests and readme. I'll do a little code review, register the package on Packagist and start some automatic code quality checks.

**Comment by iWader** [comment]
Think the code is in a good place as well as the readme. I may add a couple more examples to the readme for each of the push notifications.

Tests for the `PubnubMessage` class are in place, but I'm not sure how to go about testing the `PubnubChannel` as it has the events there.

**Comment by iWader** [comment]
Okay, I wrote tests for the events and subsequently removed as I just saw they're now in the core. Applied updates from the skeleton repo too.
