### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pubnub#5]
Hi @iWader 	  

Are you still interested in maintaining this package?

If so, could we add support for laravel 5.5+ and 6.0?

Thanks!

**Comment by atymic** [comment]
cc @iWader

**Comment by iWader** [comment]
Hi,

This package was never published/reviewed when the laravel-notification-channels was setup. Feel free to take the package over. Not sure who is running the org now but I don't have admin permissions to give you access to the repo.

**Comment by atymic** [comment]
No worries, thanks for the update!
